language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: Zinjo4UIBKDw7lf1z9BjAmQateGtM4jV0Jj6BpuLDsXyplVS0cBZWb6r7G9PGCRAZPJsVkK+nqNhF0f8Bs3dHYj6tXgAaQHlSa10LS4B79KImVUXCwtt0+TJ/wKDqDqkU1vY33fsH9Jxgh5QWVjWJw4jKb8HBqy5LmHd6iM3A3A=
  on:
    tags: true
    all_branches: true
    repo: Brightspace/free-range-app-utils
