language: node_js
node_js:
- '0.12'
after_success: npm run report-coverage
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: ZuIG9qg5f4WpXa9c9PUVCFvQICTjbpOm5zlxaKQJ8aPn9wy8yocBjUylsqvR7nyUFLrvI4hUtvLxJEVwYeyQ2PiHcgWattd/5B3I8UObNcc2XXplx6sDTKqgXyF21GNzY/M0OtAR2+aVYRXWIvWGC12Fhg/H1wAjGhjwS+HKst8=
  on:
    tags: true
    all_branches: true
    repo: Brightspace/free-range-app-utils
